// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EqualizerController from "./equalizer_controller"
application.register("equalizer", EqualizerController)

import PickerController from "./picker_controller"
application.register("picker", PickerController)

import PromptController from "./prompt_controller"
application.register("prompt", PromptController)
